apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulytix-fortend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neb-fortend
  template:
    metadata:
      labels:
        app: neb-fortend
    spec:
      containers:
        - name: neb-fortend
          image: 935743309939.dkr.ecr.ap-south-1.amazonaws.com/nebulytixfortend:latest
          ports:
            - containerPort: 5054
       