apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulytix-fortend
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: neb-fortend
  strategy:
    type: RollingUpdate
    rollingUpdate:    
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: neb-fortend
    spec:
      containers:
        - name: neb-fortend
          image: 935743309939.dkr.ecr.ap-south-1.amazonaws.com/nebulytixfortend:latest
          ports:
            - containerPort: 80
       